manifestUrl=https://raw.githubusercontent.com/AndrewImm-OP/minecraft-pack-dist/main/manifest.json
publicKeyBase64=MCowBQYDK2VwAyEAYVO/ufefLk3ziyWx9mhQs83hCUeHj+MS+mxeTtBVmKc=
connectTimeoutSeconds=8
requestTimeoutSeconds=30
networkFailurePolicy=allow
